### ISSUE TITLE
Non-existing python dependency: PIL==7.0.0

### ISSUE THREAD

**Issue by vniclas** [tasostefas/opendr_internal#109]
Hi @Pavlos-Tosidis (tagging you as you are listed as the last person editing the [dependency file](https://github.com/tasostefas/opendr_internal/blob/d38045dfc51ffa4ef2f1fc134636c8fb1c73d624/src/opendr/perception/face_recognition/dependencies.ini)).

The package `PIL==7.0.0` does not exist. This should probably be replaced with `pillow==7.0.0`.

**Comment by Pavlos-Tosidis** [comment]
You are absolutely right, I will change it on my next PR.

**Comment by vniclas** [comment]
FYI, I'm also addressing this in PR #112
