### ISSUE TITLE
Tests cancel after 360 m

### ISSUE THREAD

**Issue by LukasHedegaard** [tasostefas/opendr_internal#123]
With a growing toolkit size, CI tests are naturally taking longer and longer. However, the test duration has now reached a point, where GitHub Actions cancels tests before they finish (after 360 minutes). This makes integration of bug-fixes or new tools impossible in the current setup, even through the tests themselves do not have errors.

A "hack" to circumvent this could be to split the Test API workflow into multiple sub-workflows, each of which test a subset of the methods, e.g. by replacing the last line in "opendr_internal/.github/workflows/tests_sources.yml" ( `python -m unittest discover -s tests/sources`) with one or more targeted tests (e.g. `python -m unittest discover -s tests/sources/tools/perception/activity_recognition`.)

**Comment by stefaniapedrazzi** [comment]
You are welcome to go ahead and implement this solution.
We could add a script in the test folder that automatically loops through all the available folders and launches the tests.
