### ISSUE TITLE
Tests stuck on activity recognition

### ISSUE THREAD

**Issue by passalis** [tasostefas/opendr_internal#127]
I think that tests now get stuck at activity recognition tests for no specific reason. I can successfully run this tests locally. However, there are three runs in which these tests seem to have stuck:

https://github.com/tasostefas/opendr_internal/pull/94/checks?check_run_id=3662854127
https://github.com/tasostefas/opendr_internal/pull/107/checks?check_run_id=3662837030
https://github.com/tasostefas/opendr_internal/pull/89/checks?check_run_id=3661815195

**Comment by passalis** [comment]
@LukasHedegaard could please take a look on this?

It seems that the tests were also failed on the recent bugfix (https://github.com/tasostefas/opendr_internal/runs/3660218030) that was merged on the master branch.

**Comment by LukasHedegaard** [comment]
My apologies, it seems I merged the branch prematurely. A PR #128 with a proposed fix has been opened.

**Comment by passalis** [comment]
#128 resolved this issue. Thank you!
