### ISSUE TITLE
Modifications for LearnerRL and BaseLearner classes

### ISSUE THREAD

**Issue by bheijden** [tasostefas/opendr_internal#79]
After having a discussing with most people working on RL in WP5 (assigned to this issue), we came to the conclusion that the current interface of the LearnerRL and BaseLearner could be modified to be more suited for RL.

I am opening this issue, and tagging all relevant people such that we can discuss this here and converge to a interface that is more suited for RL and user-friendly. 

@stefaniapedrazzi, @passalis I've included both of you, as i figure you can be helpful in the discussion as you know more about the reason for certain design decisions made earlier in the project.

I will post my concerns with the current implementation at a later moment in a separate response below and encourage all other people to do the same!

**Comment by ad-daniel** [comment]
Going for option 1, other than updating the specifications accordingly, is any change required at the level of the codebase? As far as I can tell no tool relies on it, nor are the classes defined.

**Comment by bheijden** [comment]
I agree that removing the RLTarget is a good solution if no one is using it.

**Comment by dHonerkamp** [comment]
Yes, don't think it needs any code changes

**Comment by ad-daniel** [comment]
I think this can be closed for now, thank you all.
