### ISSUE TITLE
Inconsistent definitions of Data and Target classes

### ISSUE THREAD

**Issue by vniclas** [tasostefas/opendr_internal#90]
Hi all,

I came across some inconsistencies between the styles used in [data.py](https://github.com/tasostefas/opendr_internal/blob/master/src/opendr/engine/data.py) and [target.py](https://github.com/tasostefas/opendr_internal/blob/master/src/opendr/engine/target.py), which make the integration of new subclasses unnecessary complicated.
While `data.py` is rather consistent and adheres to the proposed usage of getter and setters, `target.py` could be improved such that the user can experience a common interface across different target classes.

In my opinion, the biggest problem is that `Target` does not mark its variables as private (leading underscore), which makes it cumbersome to implement proper getter/setter functions to perform type checking. I'd propose to change `Target` to the code below and add default setter/getters as has been done in the `Data` class.

```
class Target(BaseTarget):
    def __init__(self):
        super().__init__()
        self._data = None
        self._confidence = None
        self._action = None
```

**Comment by passalis** [comment]
Hi @vniclas,

You are correct.  `Target` should implement setters/getters as you describe. I have opened #98 where I implemented setters and getters for the base classes, as well as for a few more used by AUTH. I think this resolves the main issue (i.e., having these fields as private variables in the `Target` class). Let me know what you think.

**Comment by vniclas** [comment]
Hi @passalis,

thanks for looking into the issue. I directly commented on your PR.
